name: moyawim2
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  flutter_spinkit: ^4.1.2+1
  firebase_auth: ^0.16.0
  cloud_firestore: ^0.13.5
  provider: ^4.0.4
  image_picker: ^0.6.5+3
  firebase_storage: ^3.1.5
  cached_network_image: ^2.1.0+1
  firebase_core: ^0.4.4+3
  email_validator: ^1.0.4
  font_awesome_flutter: ^8.8.1
  image_cropper: ^1.2.1

dev_dependencies:
  mailer: ^3.0.3
  flutter_mailer: ^0.4.1+1
  url_launcher: ^5.4.1
  splashscreen: ^1.2.0
  intro_views_flutter: '^2.8.1'
  #  liquid_swipe: ^1.3.1
  shared_preferences: 0.5.6+3
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
   - assets/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
